apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops-journal-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/plasterinho/cluster-config.git'
    targetRevision: main
    path: gitops/environments/prod

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ops-journal-prod

