apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    
    scrape_configs:
      - job_name: 'ops-journal'
        static_configs:
          - targets: 
              - 'ops-journal.default.svc.cluster.local:80'