apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    
    scrape_configs:
      - job_name: 'ops-journal'
        static_configs:
          - targets: 
              - 'ops-journal.ops-journal-dev.svc.cluster.local:80'
            labels:
              env: 'dev'

          - targets:
              - 'ops-journal.ops-journal-staging.svc.cluster.local:80'
            labels:
              env: 'staging'

          - targets:
              - 'ops-journal.ops-journal-prod.svc.cluster.local:80'
            labels:
              env: 'prod'