resources:
  - ../../base
  - namespace.yaml

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: ops-journal
  - path: env.patch.yaml
    target:
      kind: Deployment
      name: ops-journal

images:
  - name: ghcr.io/plasterinho/ops-journal
    newTag: sha-67af2f5

  - name: ghcr.io/plasterinho/ops-journal-metrics
    newTag: sha-67af2f5
