resources:
  - ../../base
  - namespace.yaml

patches:
  - path: replicas.yaml

images:
  - name: ghcr.io/plasterinho/ops-journal
    newTag: sha-ef92236

  - name: ghcr.io/plasterinho/ops-journal-metrics
    newTag: sha-ef92236
