# Orphaned values - these are not used by the Argo CD Application,
# but are here for reference and future use if needed.
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    path_prefix: /tmp/loki
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    volume_enabled: true
  rulerConfig:
    wal:
      dir: /tmp/loki/ruler-wal

singleBinary:
  replicas: 1
  persistence:
    enabled: false

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

gateway:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false
